# Serena MCP Server - プロジェクト設定
# このファイルは各プロジェクトごとにカスタマイズしてください

# ===============================
# 言語設定
# ===============================
# 対応言語: typescript, python, java, cpp, rust, go, php など
languages:
- typescript

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: 'utf-8'

# ===============================
# Gitignore連携
# ===============================
# trueの場合、.gitignoreのパターンを自動的に適用
ignore_all_files_in_gitignore: true

# ===============================
# 追加の除外パス
# ===============================
ignored_paths:
  # 依存関係
- 'node_modules/'
- '.pnpm-store/'
- '.yarn/'
- 'vendor/'
- '__pycache__/'
- '.venv/'
- 'venv/'
- '.next/'
- 'out/'
- 'build/'
- 'dist/'
- 'target/'
- 'bin/'
- 'obj/'
- 'tests/'
- 'test-results/'
- 'playwright-report/'
- 'coverage/'
- '__tests__/'
- '*.test.ts'
- '*.test.tsx'
- '*.test.js'
- '*.test.jsx'
- '*.spec.ts'
- '*.spec.tsx'
- '*.spec.js'
- '*.spec.jsx'
- 'logs/'
- '*.log'
- '*.log.*'
- '*.pdf'
- '*.mp4'
- '*.mp3'
- '*.zip'
- '*.tar.gz'
- '.cache/'
- 'tmp/'
- 'temp/'
- '.parcel-cache/'
- '.turbo/'
- '*.tsbuildinfo'
- '*.db'
- '*.sqlite'
- '*.sqlite3'
- 'postgres_data/'
- 'pgdata/'
- 'data/'
- 'uploads/'
- 'public/uploads/'
- '.vscode/'
- '.idea/'
- '.claude/sessions/'
- '.claude/plans/'
- '.claude/file-history/'
- '*.swp'
- '*.swo'
- '*~'
- '.DS_Store'
- 'Thumbs.db'
- '._*'
- 'Desktop.ini'
- '.env*'

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# ===============================
# 除外ツール
# ===============================
# メモリ削減のため、不要なツールを除外
# read_only: true の場合、編集系ツールは自動的に無効化される
excluded_tools:
  # シェル実行（セキュリティリスクあり）
  # - execute_shell_command
  # 編集系（read_only: true で自動無効化）
  # - create_text_file
  # - delete_lines
  # - insert_after_symbol
  # - insert_at_line
  # - insert_before_symbol
  # - replace_lines
  # - replace_symbol_body
  # メモリ関連（必要に応じて）
  # - write_memory
  # - delete_memory
  # オンボーディング（初回のみ必要）
  # - onboarding
  # その他（必要に応じて）
  # - summarize_changes
  # - think_about_collected_information
  # - think_about_task_adherence
  # - think_about_whether_you_are_done

# ===============================
# 初期プロンプト
# ===============================
# プロジェクト固有の指示がある場合に設定
initial_prompt: ''

# ===============================
# プロジェクト名
# ===============================
# 自動的にディレクトリ名が使用される
project_name: ''

# ===============================
# オプショナルツール
# ===============================
# 追加で有効化したいツールがある場合
included_optional_tools: []

# list of mode names to that are always to be included in the set of active modes
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the base_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this setting overrides the global configuration.
# Set this to [] to disable base modes for this project.
# Set this to a list of mode names to always include the respective modes for this project.
base_modes:

# list of mode names that are to be activated by default.
# The full set of modes to be activated is base_modes + default_modes.
# If the setting is undefined, the default_modes from the global configuration (serena_config.yml) apply.
# Otherwise, this overrides the setting from the global configuration (serena_config.yml).
# This setting can, in turn, be overridden by CLI parameters (--mode).
default_modes:

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []
